name: 提取频道
on:
  push:
    paths:
      - '.github/workflows/channels.yml'
      - 'process_channels.py'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  update-channels:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml tqdm aiohttp beautifulsoup4 lxml tenacity cachetools requests-toolbelt numba



      - name: 运行频道处理脚本
        run: |
          python process_channels.py

      - name: 提交并推送更改
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update IPTV channels list"
            git push origin main
          else
            echo "没有文件更改，无需提交。"
          fi
