name: zhixue

on:
  schedule:
  # 每天 UTC 时间 5:30 运行（即美国东部时间 0:30）
  - cron: '30 5 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install --upgrade pip
      
      - name: Run main
        run: python ${{ github.workspace }}/main.py

                               
      - name: 提交更改
        run: |
          git config --local user.email "quwuping11@gmail.com"
          git config --local user.name "qingtingjjjjjjj"
          git add .
          git commit *.txt -m "Add generated file"
          git push -f
